version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - imperial
    profiles:
      - dev

  web:
    depends_on:
      - db
    image: imperial-union:latest
    build:
      context: ./
      dockerfile: docker/imperial-union-app/Dockerfile
    container_name: imperial-union-app
    ports:
      - '8082:8080'
    networks:
      - imperial
    profiles:
      - dev

networks:
  imperial:
    driver: bridge
